export { default as CardPokemon } from './CardPokemon/CardPokemon.component';
export { default as Text } from './Text/Text.component';
export { default as PokemonNotFound } from './PokemonNotFound/PokemonNotFound.component';
export { default as Tag } from './Tag/Tag.component';
export { default as Error } from './Error/Error.component';
export { default as Loading } from './Loading/Loading.component';
export { default as Input } from './Input/Input.component';
export { default as ProviderThemeJest } from './ProviderThemeJest/ProviderThemeJest.component';
export { default as Layout } from './Layout/Layout.component';
